name: PR validate - API

on:
  pull_request:
    branches:
      - main
    paths:
      - 'API/**'

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore API/WasteFree.sln

      - name: Build API
        run: dotnet build API/WasteFree.sln --configuration Release --no-restore

      - name: Publish API
        run: dotnet publish API/WasteFree.Api/WasteFree.Api.csproj --configuration Release --output ./publish

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/wastefree-api:latest -f API/Dockerfile ./API