name: Build and Push UI Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: cd UI && npm ci

      - name: Build UI
        run: cd UI && npm run build --if-present

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/wastefree-ui:latest -f UI/Dockerfile UI

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/wastefree-ui:latest

      - name: Add known hosts
        run: |
          set -e
          HOST="${{ secrets.DEPLOY_HOST }}"
          PORT="${{ secrets.DEPLOY_PORT }}"; [ -z "$PORT" ] && PORT=10222
          if [ -z "$HOST" ]; then echo "ERROR: DEPLOY_HOST pusty" >&2; exit 1; fi
          mkdir -p ~/.ssh
          if [ -n "${{ secrets.DEPLOY_KNOWN_HOST }}" ]; then
            echo "${{ secrets.DEPLOY_KNOWN_HOST }}" >> ~/.ssh/known_hosts
          else
            ssh-keyscan -T 5 -p "$PORT" -t ed25519 -H "$HOST" 2>/dev/null >> ~/.ssh/known_hosts || true
          fi
          grep -q "$HOST" ~/.ssh/known_hosts || { echo "Brak wpisu hosta (użyj sekretu DEPLOY_KNOWN_HOST)." >&2; exit 1; }

      - name: Start ssh agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy API over SSH
        uses: appleboy/ssh-action@v1
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script_stop: true
          envs: DOCKERHUB_USERNAME
          script: |
            set -euo pipefail

            U=$(printf "%s" "${DOCKERHUB_USERNAME}" | tr -d '\r\n' | tr '[:upper:]' '[:lower:]')
            if [ -z "$U" ]; then
              echo "::error::DOCKERHUB_USERNAME is empty"
              exit 1
            fi
            IMAGE="${U}/wastefree-api:latest"
            echo "Using IMAGE=${IMAGE}"

            # zatrzymaj i usuń stary kontener, jeśli istnieje
            docker stop wastefree-api || true
            docker rm wastefree-api || true

            docker pull "$IMAGE"
            docker run -d --name wastefree-api -p 8080:80 "$IMAGE"
            docker image prune -f || true