name: Build and Deploy UI Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: cd UI && npm ci

      - name: Build UI
        run: cd UI && npm run build --if-present

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/wastefree-ui:latest -f UI/Dockerfile UI

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/wastefree-ui:latest

      - name: Deploy API over SSH
        uses: appleboy/ssh-action@v1
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script_stop: true
          envs: DOCKERHUB_USERNAME
          script: |
            set -euo pipefail

            U=${DOCKERHUB_USERNAME,,}

            IMAGE="${U}/wastefree-ui:latest"
            echo "Using IMAGE=${IMAGE}"

            docker stop wastefree-ui || true
            docker rm wastefree-ui || true

            docker pull "$IMAGE"
            docker run -d --restart unless-stopped --name wastefree-ui -p 5000:80 "$IMAGE"
            docker image prune -f || true